version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ticketdb-postgres
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chikku
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: ticketmanager-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticketdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: chikku
    depends_on:
      - postgres